services:
  # Core services
  ultron-attendant:
    image: ultron-attendant
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ULTRON_SERVER_ADDRESS: ${ULTRON_SERVER_ADDRESS}
      ULTRON_SERVER_REDIS_ADDRESS: ${ULTRON_SERVER_REDIS_ADDRESS}
      ULTRON_SERVER_REDIS_PASSWORD: ${ULTRON_SERVER_REDIS_PASSWORD}
      EMMA_CLIENT_ID: ${EMMA_CLIENT_ID}
      EMMA_CLIENT_SECRET: ${EMMA_CLIENT_SECRET}
    networks:
      - ultron
      
networks:
  ultron: