services:
  # Core services
  ultron-attendant:
    image: ultron-attendant
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ULTRON_SERVER_ADDRESS: ultron:8443
      ULTRON_REDIS_SERVER_ADDRESS: redis:6379
    networks:
      - ultron
      
networks:
  ultron:
    external:
      name: ultron
